### ISSUE TITLE
Create Databases

### ISSUE THREAD

**Issue by dius00** [dius00/API_Night_MyMizu#1]
- [x] Create Team Table containing `name` `id` `members`

- [x] Create Weekly Leaderboad Table: `team_id` `team_volume`

**Comment by kenny01123** [comment]
just implemented a simple CRUD and deployed to the firebase project. (and hard coded some seed) 
Will do the mymizu api linkage tomorrow.

Since in tables we have a method `orderByValue` to make the leaderboard, I guess we don't need to make a Weekly Leaderboad table?
