### ISSUE TITLE
Integrate Authentication

### ISSUE THREAD

**Issue by dius00** [dius00/API_Night_MyMizu#3]
- [ ] Integrate Firebase Authentication

**Comment by dhequex** [comment]
Having issues with the relative import of Authentication context into Signup component. 

`import { useAuth } from "./Authentication/AuthContext.js";`

`Failed to compile.

./src/components/Landing/Signup.js
Module not found: Can't resolve './Authentication/AuthContext.js' in '/Users/3301hakuba/Dropbox/CC15/API_Night_MyMizu/src/components/Landing'
`

**Comment by dius00** [comment]
Resolved!
